[package]
name = "jsonschema2avro"
version = "0.1.0"
edition = "2021"

[features]
default = []
cli = ["clap"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.5"
reqwest = { version = "0.12", features = ["blocking", "json"] }
json-ptr = "0.3"
itertools = "0.14"
anyhow = "1.0"
regex = { version = "1.11.2", features = ["std"], default-features = false }
xxhash-rust = { version = "0.8.15", features = ["xxh64"] }

# Optional dependencies
clap = { version = "4", features = ["derive"], optional = true }

[dev-dependencies]
assert_cmd = "2"
tempfile = "3"
predicates = "3"
insta = { version = "1", features = ["json"] }